name: LearnIT
channels:
  - defaults
dependencies:
  - python=3.11
  - flask
  - python-dotenv
  - tiktoken
  - OpenAI
  - chardet
  - cchardet
  - pypdf
  - pypdfium2
  - black
  - xenon
  - pydantic
  - pydantic[email]
  - fastapi
  - python-jose[cryptography]
  - passlib[bcrypt]
  - passlib
  - bcrypt
  - pymongo[srv]