name: LearnIT
channels:
  - defaults
dependencies:
  - python=3.11
  - flask
  - python-dotenv
  - tiktoken
  - OpenAI
  - chardet
  - cchardet
  - tiktoken
  - dotenv
  - pypdf
  - pypdfium2
  - black
  - xenon
  - pydantic
  - fastapi