DATASETS_PATH = "./datasets"
SCI_TLDR_PATH = "./datasets/SCI_scitldr"
SCI_TLDR_REF_PATH = "./datasets/SCI_scitldr/SciTLDR-FullText"
SCI_TLDR_SUM_PATH = "./datasets/SCI_scitldr/SciTLDR-AIC"
BILL_SUM_PATH = "./datasets/LGL_bill_sum"
GOV_REPORT_PATH = "./datasets/LGL_gov_report/gov-report/crs"
BOOK_SUM_PATH = "./datasets/SCI_book_sum"
LONG_SUM_ARXIV_PATH = "./datasets/SCI_longsum_arxiv"
LONG_SUM_PUBMED_PATH = "./datasets/SCI_longsum_pubmed"

REFERENCES_PATH = "./extracted_data/references"
SUMMARIES_PATH = "./extracted_data/summaries"
LOGS_PATH = "./extracted_data"

TEST_PARAMS_PATH = "./extracted_data/params_test.txt"
TEST_FINAL_PATH = "./extracted_data/final_test.txt"

OUTPUT_PATH = "./output_data"
OUTPUT_PARAMS_TEST_PATH = "./output_data/params_test"
OUTPUT_FINAL_TEST_PATH = "./output_data/final_test"
OUTPUT_PATH_1 = "./output_data/0"
OUTPUT_PATH_3 = "./output_data/1"
OUTPUT_PATH_2 = "./output_data/2"

ERROR_LOGS = "error_logs.txt"
ID_LOGS = "ids.txt"
